# Blocks: String list:  Name of block, not ID for now.
# multiplier: double (integer or floating point):  Number to multiply chance of getting reward by.
# Rewards: section: put rewards in this format:
# Rewards:
#     (name):
#         chance: double (integer or floating point):  Chance out of 100 for the reward to be triggered.
#         commands: String list:  Command(s) to run if reward is triggered.
# (end of reward #1)
#     (add more rewards to your preference)
# (end of reward section)
# debug:  boolean (true or false):  Whether to enable debug mode or not.  Debug mode gives extensive details about the reward chance calculation process as it happens.
Blocks:
  - cobblestone
  - stone
  - mossy_cobblestone
multiplier: 1
Rewards:
  '1':
    chance: 5
    commands:
      - token give %player% 10
      - eco give %player% 2000
      - broadcast %player% received rewards
  '2':
    chance: 20
    commands:
      - eco give %player% 500
debug: false