# globalAllowedWorlds: string list: a list of worlds all rewards will operate in.  Is overridden by allowedWorlds in a reward section.  Defaults to "*", meaning all worlds allowed.
# globalAllowedRegions: string list: same as globalAllowedWorlds except with WorldGuard regions instead of worlds.
# globalSilkTouch: string, can be REQUIRED, IGNORED, or DISALLOWED: The global setting on whether silk touch is required, disallowed, or ignored to receive rewards.  Is overrided by silkTouch in a reward section or reward.  Defaults to IGNORED.
# removeInvalidValues: boolean: If true, will delete invalid blocks in the lists of blocks.
# multiplier: double (integer or floating point):  Number to multiply chance of getting reward by.
# survivalOnly: boolean:  If the reward should only be enabled when the player is in survival mode.
# verbosity:  number (0, 1, or 2) (default 1):  How verbose console messages should be.  0 for none except errors, 1 for errors and executed commands, 2 for a metric ton of logging detail. (probably don't use 2 in production.)
# Please note that even with verbosity: 0 you will still receive command output in console.  ex. if you have in a reward /give %player% diamond, you will still receive the message "Gave 1 [Diamond] to %player%" every time it runs. If you find a way to prevent the command output, message me on Spigot.
# (rewardSectionName): section: put rewards in this format:
# (rewardSectionName):
#   (name):
#       blocks: String list:  Name of block to trigger rewards.  You can use :s in name to indicate data values.  Note this will change in 1.13.
#       allowedWorlds: string list: a list of worlds this reward section will operate in.  Defaults to "*", meaning it will operate in any world.
#       silkTouch: string, can be REQUIRED, IGNORED, or DISALLOWED:  Sets whether silk touch is required, ignored, or prevented from receiving a reward in this section.  Overrides globalSilkTouch, is overriden by silkTouch in a reward under this section.  Defaults to IGNORED.
#       rewards:
#           (individualname):
#               chance: double (integer or floating point):  Chance out of 100 for the reward to be triggered.
#               commands: String list:  Command(s) to run if reward is triggered.
#               silkTouch: string, can be REQUIRED, IGNORED, OR DISALLOWED:  Sets whether a silk touch pickaxe is required, ignored, or prevented from receiving this reward.  Overrides globalSilkTouch and silkTouch in parent reward section.  Defaults to IGNORED.
#           (individualname2):
#               chance: double (integer or floating point):  Chance out of 100 for the reward to be triggered.
#               commands: String list:  Command(s) to run if reward is triggered.
#               silkTouch: string, can be REQUIRED, IGNORED, OR DISALLOWED:  Sets whether a silk touch pickaxe is required, ignored, or prevented from receiving this reward.  Overrides globalSilkTouch and silkTouch in parent reward section.  Defaults to IGNORED.
#           (etc.)
#   (end of reward section #1)
#     (add more rewards to your preference)
removeInvalidValues: false
multiplier: 1
survivalOnly: true
validateWorldsAndRegions: true
verbosity: 1
genericRewards:
    blocks:
        - cobblestone
        - stone
        - mossy_cobblestone
    allowedWorlds:
        - "*"
    silkTouch: DISALLOWED
    rewards:
        bigreward:
            chance: 5
            commands:
                - eco give %player% 2000
                - broadcast %player% received rewards
        smallreward:
            chance: 20
            commands:
                - eco give %player% 500
cropRewards:
    blocks:
        - "wheat:true"
    allowedWorlds: 
        - farming1
        - farming23
        - world_the_end
    rewards:
        farming:
            chance: 1
            commands:
                - eco give %player% 34095
                - broadcast %player% likes to farm!
