name: CommandMineRewards
main: me.AlanZ.CommandMineRewards.CommandMineRewards
author: AlanZ
version: 5.1
api-version: 1.13
softdepend: [WorldGuard]
commands:
    cmr:
        description: The command for utilizing CMR
        usage: /<command> [args...]
permissions:
    cmr.*:
        default: OP
        children:
            cmr.use.*: true
            cmr.reload: true
            cmr.modifyblocks: true
            cmr.modifyrewards: true
            cmr.modifycommands: true
            cmr.modifychance: true
            cmr.modifymultiplier: true
            cmr.modifyallowedworlds: true
            cmr.modifyallowedregions: true
            cmr.viewblocks: true
            cmr.viewrewards: true
            cmr.viewcommands: true
            cmr.viewchance: true
            cmr.viewmultiplier: true
            cmr.viewallowedworlds: true
            cmr.viewallowedregions: true
    cmr.use.*:
        description: Makes you eligible for all rewards in CommandMineRewards.
        default: OP
    cmr.reload:
        description: The permission required to reload the CMR config.
        default: OP
    cmr.modifymultiplier:
        description: The permission required to adjust the reward chance multiplier.
        default: OP
    cmr.viewmultiplier:
        description: The permission required to view the reward chance multiplier.
        default: OP
    cmr.modifyblocks:
        description: The permission required to edit the list of blocks that trigger rewards.
        default: OP
    cmr.viewblocks:
        description: The permission required to view the list of blocks which trigger rewards.
        default: OP
    cmr.modifyrewards:
        description: The permission required to create or delete rewards.  Be careful who you give this to!
        default: OP
    cmr.viewrewards:
        description: The permission required to see the list of rewards.
        default: OP
    cmr.modifycommands:
        description: The permission required to add and remove commands from rewards.
        default: OP
    cmr.viewcommands:
        description: The permission required to see all commands added to all rewards.
        default: OP
    cmr.modifychance:
        description: The permission required to change the chance value in a reward.
        default: OP
    cmr.viewchance:
        description: The permission required to view the chance value in a reward.
        default: OP
    cmr.modifyallowedworlds:
        description: The permission required to add and remove worlds from the global and per-reward-section allowed worlds lists.
        default: OP
    cmr.viewallowedworlds:
        description: The permission required to see the global and per-reward-section allowed worlds lists.
        default: OP
    cmr.modifyallowedregions:
        description: The permission required to add and remove regions from the global and per-reward-section allowed regions lists.
        default: OP
    cmr.viewallowedregions:
        description: The permission required to see the global and per-reward-section allowed regions lists.
        default: OP