name: CommandMineRewards
main: me.Datatags.CommandMineRewards.CommandMineRewards
author: Datatags
version: 6.4
api-version: 1.13
softdepend: [WorldGuard]
commands:
    cmr:
        description: The command for utilizing CMR
        usage: /<command> [args...]
permissions:
    cmr.seeall:
        description: Allows you the permission to see everything related to CMR but not change it.
        default: OP
        children:
            cmr.help: true
            cmr.block: true
            cmr.reward: true
            cmr.command: true
            cmr.multiplier: true
            cmr.world: true
            cmr.region: true
    cmr.admin:
        description: Allows you to use any CMR commands
        default: OP
        children:
            cmr.*: true
    cmr.help:
        description: Allows you to see the help for commands you have permission to use.
        default: true
    cmr.reload:
        description: The permission required to reload the CMR config.
        default: OP
    cmr.multiplier.modify:
        description: The permission required to adjust the reward chance multiplier.
        default: OP
    cmr.multiplier:
        description: The permission required to view the reward chance multiplier.
        default: OP
    cmr.block.modify:
        description: The permission required to edit the list of blocks that trigger rewards.
        default: OP
    cmr.block:
        description: The permission required to view the list of blocks which trigger rewards.
        default: OP
    cmr.reward.modify:
        description: The permission required to create or delete rewards.  Be careful who you give this to!
        default: OP
    cmr.reward:
        description: The permission required to see the list of rewards.
        default: OP
    cmr.command.modify:
        description: The permission required to add and remove commands from rewards.
        default: OP
    cmr.command:
        description: The permission required to see all commands added to all rewards.
        default: OP
    cmr.world.modify:
        description: The permission required to add and remove worlds from the global and per-reward-section allowed world lists.
        default: OP
    cmr.world:
        description: The permission required to see the global and per-reward-section allowed world lists.
        default: OP
    cmr.region.modify:
        description: The permission required to add and remove regions from the global and per-reward-section allowed region lists.
        default: OP
    cmr.region:
        description: The permission required to see the global and per-reward-section allowed region lists.
        default: OP
    cmr.silktouchpolicy:
        description: The permission required to see the silk touch requirement of a reward or globally.
        default: OP
    cmr.silktouchpolicy.modify:
        description: The permission required to change the silk touch requirement of a reward or globally.
        default: OP
