name: CommandMineRewards
main: me.datatags.commandminerewards.CommandMineRewards
author: Datatags
version: 7.0
api-version: 1.13
softdepend: [WorldGuard, mcMMO]
commands:
    cmr:
        description: The command for utilizing CMR
        usage: /<command> [args...]
permissions:
    cmr.seeall:
        description: Allows you the permission to see everything related to CMR but not change it.
        children:
            cmr.help: true
            cmr.block: true
            cmr.reward: true
            cmr.command: true
            cmr.multiplier: true
            cmr.world: true
            cmr.region: true
            cmr.limit: true
            cmr.gui: true
            cmr.silktouchpolicy: true
    cmr.help:
        description: Allows you to see the help for commands you have permission to use.
        default: true
    cmr.reload:
        description: The permission required to reload the CMR config.
    cmr.multiplier.modify:
        description: The permission required to adjust the reward chance multiplier.
    cmr.multiplier:
        description: The permission required to view the reward chance multiplier.
    cmr.block.modify:
        description: The permission required to edit the list of blocks that trigger rewards.
    cmr.block:
        description: The permission required to view the list of blocks which trigger rewards.
    cmr.reward.modify:
        description: The permission required to create or delete rewards.  Be careful who you give this to!
    cmr.reward:
        description: The permission required to see the list of rewards.
    cmr.command.modify:
        description: The permission required to add and remove commands from rewards.
    cmr.command.execute:
        description: The permission required to trigger reward commands to run from the console.
    cmr.command:
        description: The permission required to see all commands added to all rewards.
        children:
            cmr.special: true
    cmr.world.modify:
        description: The permission required to add and remove worlds from the global and per-reward-section allowed world lists.
    cmr.world:
        description: The permission required to see the global and per-reward-section allowed world lists.
    cmr.region.modify:
        description: The permission required to add and remove regions from the global and per-reward-section allowed region lists.
    cmr.region:
        description: The permission required to see the global and per-reward-section allowed region lists.
    cmr.silktouchpolicy:
        description: The permission required to see the silk touch requirement of a reward or globally.
    cmr.silktouchpolicy.modify:
        description: The permission required to change the silk touch requirement of a reward or globally.
    cmr.special:
        description: Allows you to use CMR built-in demo commands, like /cmr special sound
    cmr.limit:
        description: The permission required to see reward limits.
    cmr.limit.modify:
        description: The permission required to adjust reward limits.
    cmr.gui:
        description: The permission required to use the CMR GUI. Permission is still required for all actions in the interface.
    cmr.gui.assist:
        description: The permission required to join someone else's GUI session. The person joining will have all permissions of the original GUI opener while in their session.
    cmr.debug:
        description: The permission required to enable CMR debug mode.
