name: Build with Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # https://github.com/gradle/gradle-build-action
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.3.2

    # https://github.com/gradle/wrapper-validation-action
    - name: Wrapper validation
      uses: gradle/actions/wrapper-validation@v3.3.2
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        java-package: jdk
        architecture: x64
        cache: gradle
    - name: Configure Git
      run: git config --global user.name "Github Actions" && git config --global user.email "actions@github.com"
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: shadowJar
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: CommandMineRewards-dev
        path: main/build/libs/CommandMineRewards-*.jar
